### ISSUE TITLE
Fatal error: listen EADDRINUSE

### ISSUE THREAD

**Issue by iDVB** [c301/grunt-webstore-upload#11]
When I execute this task it *does* open the browser to the confirm page, but I get the console err...
`Fatal error: listen EADDRINUSE`

Also, when I authorize in the browser, it just hangs forever. I only have these two Redirect urls in Developer Dash...
```
urn:ittf:wg:oauth:2.0:oob
http://localhost
```

Rerunning after authorizing has the same affect.

**Comment by c301** [comment]
What version of the plugin do you use? 
Can you get latest version ( 0.8.3 - just published ) from npm and try? 

Looks like network post, used by plugin, already in use.

**Comment by iDVB** [comment]
Sure.... just got it to work by forking and changing the PORT number. No idea whats using that port but changing it to `8675` worked for me.

**Comment by c301** [comment]
Please confirm, that you have a problem with port **14809** ( it was **8080** in early version )
https://github.com/c301/grunt-webstore-upload/blob/master/tasks/webstore_upload.js#L422

**Comment by iDVB** [comment]
Sorry, yes, that 14809 port works fine as well. Likely better to just use a random open port, no? Or expose that as a plugin property?
