### ISSUE TITLE
refresh_token is never used?

### ISSUE THREAD

**Issue by iDVB** [c301/grunt-webstore-upload#13]
setting this doesn't seem to do anything.

Just stubbed code?

**Comment by pimterry** [comment]
Yes it is, see https://github.com/c301/grunt-webstore-upload/blob/master/tasks/webstore_upload.js#L189, and the full commit adding the functionality at https://github.com/c301/grunt-webstore-upload/commit/517fdaf82598e57c5eb54532e4a9d5da99550697, a few weeks ago.

Can't speak for cli_auth, but I've just found this up and I'm using refresh_token very successfully (and remarkably easily, I might add). It's definitely a working feature.

**Comment by c301** [comment]
yeah, I can confirm that `refresh_token` works as expected
