### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by bfred-it** [c301/grunt-webstore-upload#14]
What do you think about making a Grunt-less version of this? I'd love to just have "webstore-upload" installed globally and runnable via CLI

**Comment by DrewML** [comment]
@bfred-it A bit late (almost an entire year), but I've published a similar project that is a [small CLI app](https://github.com/DrewML/chrome-webstore-upload-cli) if you're still looking.

**Comment by bfred-it** [comment]
Thank you! Many wanted it here too: https://github.com/sindresorhus/module-requests/issues/66
