### ISSUE TITLE
Problem with version 0.9.11

### ISSUE THREAD

**Issue by bhollis** [c301/grunt-webstore-upload#19]
Hi! We've been happily using grunt-webstore-upload for the Destiny Item Manager extension for quite a while, and it's worked great. I wanted to let you know that we hit a problem after upgrading to version 0.9.11, though - all of a sudden we now get "Warning: Configuration for "beta" not exist, please check configuration of the extensions list" and the upload fails. Downgrading to 0.9.9 restores functionality.

You can see our Gruntfile here:
https://github.com/DestinyItemManager/DIM/blob/dev/Gruntfile.js

**Comment by c301** [comment]
Thanks for feedback.
Could you try `0.9.12`? It should work

**Comment by bhollis** [comment]
Wow, thanks for the fast turnaround! Looks like it all works now.
